apiVersion: v1
kind: Service
metadata:
  name: brain-tumor-service
spec:
  type: NodePort
  selector:
    app: brain-tumor-detection
  ports:
    - protocol: TCP
      port: 8001        # Port the Service exposes internally
      targetPort: 8001  # Port the container is listening on
      nodePort: 30001   # Static port accessible from outside the cluster (Kind/Minikube)
